---
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - ROLE_NAME: remi_repo
  matrix:
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: centos:6
    - MOLECULE_DISTRO: fedora:26
    - MOLECULE_DISTRO: fedora:27
    - MOLECULE_DISTRO: fedora:28

install:
  - pip install testinfra molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME ericsysmin.$ROLE_NAME
  - cd ericsysmin.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
